// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebShopMVC.Models
{
    public partial class Categories
    {
        [Key]
        public int CategoryId { get; set; }
        [Required]
        [StringLength(15)]
        public string Name { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
    }
}